module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  coreconcepts: [{ type: "autogenerated", dirName: "core-concepts" }],
  developers: [{ type: "autogenerated", dirName: "developers" }],
  routers: [{ type: "autogenerated", dirName: "routers" }],
  resources: [{ type: "autogenerated", dirName: "resources" }],
};
